dependencies = {
    layers:  [
        {
	        name: "../agua_dojo_dijit.js",
            dependencies: [
				"dojox.widget.Dialog",
				"dijit.form.Button",
				"dijit.form.TextBox",
				"dojo.fx.easing",
				"dojox.timing.Sequence",
				"dojox.data.FileStore",
				"dojo.dnd.Source",
				"dojo.dnd.Moveable",
				"dojo.dnd.Mover",
				"dojo.dnd.move",
				"dijit.Tooltip",
				"dijit.layout.LayoutContainer",
				"dijit.layout.ContentPane",
				"dijit.TitlePane",
				"dojox.widget.FisheyeLite",
				"dojo.data.ItemFileReadStore",
				"dijit.form.ComboBox",
				"dojox.layout.ResizeHandle",
				"dijit.Editor",
				"dijit.form.DateTextBox",
				"dijit.form.Textarea",
				"dijit.form.ValidationTextBox",
				"dijit.form.NumberTextBox",
				"dijit.form.CurrencyTextBox",
				"dojo.currency",
				"dijit.Dialog",
				"dijit.Tree",
				"dijit.layout.AccordionContainer",
				"dijit.layout.TabContainer",
				"dijit.layout.BorderContainer",
				"dojox.layout.FloatingPane",
				"dojox.rpc.Service",
				"dojo.io.script",
				"dojox.layout.ExpandoPane",
				"dijit.layout.SplitContainer",
				"dojo.parser",
				"dijit._base.place",
				"dojox.widget.Standby",
				"dijit.Toolbar",
				"dojox.widget.Toaster",
				"dijit.dijit",
				"dijit.form.CheckBox",
				"dijit.form.RadioButton",
				"dijit.form.Slider",
				"dijit.form.FilteringSelect",
				"dijit.form.NumberSpinner",
				"dijit.Menu",
				"dijit.ColorPalette",
				"dojo.data.ItemFileWriteStore",
				"dojox.grid.DataGrid",
				"dojox.timing",
				"dojo.cookie",
				"dojox.form.Uploader",
				"dojox.form.uploader.FileList",
				"dijit.form.SimpleTextarea",
				"dojo.io.iframe",
				"Agua.cookie",
				"dojox.widget.RollingList",
				"dojo.i18n",
				"dijit.InlineEditBox",
				"dojo._base.fx",
				"dojo._base.html",
				"dojo.dnd.Selector",
				"dojo.dnd.common",
				"dojo.dnd.autoscroll",
				"dojo.dnd.Avatar",
				"dojox.layout.GridContainer",
				"dojox.io.windowName",
				"dojox.fx.easing"

            ]
        }
    ],

    prefixes: [
        [ "dijit", "../dijit" ],
        [ "dojox", "../dojox" ],
        [ "plugins", "../../plugins" ]
    ]
};